version: 2
updates:
    - package-ecosystem: "pip"
      directory: "/"
      schedule:
          interval: "weekly"
      groups:
          all-dependencies:
              patterns:
                  - "*"
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"
      groups:
          all-actions:
              patterns:
                  - "*"
      commit-message:
          prefix: "[ci skip]"
