from argparse import Namespace
from asyncio import AbstractEventLoop
from blinkpy.blinkpy import Blink
import concurrent.futures
from datetime import datetime
from logging import Logger
from mqtt_helper import MqttHelper
from paho.mqtt.client import Client, MQTTMessage, ConnectFlags, DisconnectFlags
from paho.mqtt.reasoncodes import ReasonCode
from paho.mqtt.properties import Properties
from types import FrameType
from typing import Protocol, Any, Callable, Coroutine, TypeVar

_T = TypeVar("_T")


class BlinkServiceProtocol(Protocol):
    api_calls: int
    args: Namespace | None
    blink_cameras: dict[str, dict[str, Any]]
    blink_config: dict[str, Any]
    blink_sync_modules: dict[str, dict[str, Any]]
    blink: Blink
    client_id: str
    config: dict[str, Any]
    device_interval: int
    device_list_interval: int
    devices: dict[str, Any]
    discovery_complete: bool
    events: list
    last_call_date: str
    logger: Logger
    loop: AbstractEventLoop
    mqtt_config: dict[str, Any]
    mqtt_connect_time: datetime
    mqtt_helper: MqttHelper
    mqttc: Client
    qos: int
    rate_limited: bool
    running: bool
    service_name: str
    service: str
    session: Any
    snapshot_update_interval: int
    states: dict[str, Any]

    async def blink_refresh(self) -> None: ...
    async def build_camera_states(self, device_id: str, camera: dict[str, str]) -> None: ...
    async def build_camera(self, camera: dict[str, str]) -> str: ...
    async def build_component(self, device: dict[str, str]) -> str: ...
    async def build_switch(self, sync_module: dict[str, str]) -> str: ...
    async def build_sync_module_states(self, device_id: str, sync_module: dict[str, str]) -> None: ...
    async def collect_all_blink_events(self) -> None: ...
    async def collect_events_loop(self) -> None: ...
    async def collect_snapshots_loop(self) -> None: ...
    async def connect(self) -> None: ...
    async def device_list_loop(self) -> None: ...
    async def device_loop(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def get_cameras(self) -> dict[str, Any]: ...
    async def get_events_from_device(self, device_id: str) -> None: ...
    async def get_nightvision(self, device_id: str) -> str: ...
    async def get_recorded_file(self, device_id: str, file: str) -> str | None: ...
    async def get_snapshot_from_device(self, device_id: str) -> str | None: ...
    async def get_sync_modules(self) -> dict[str, Any]: ...
    async def handle_blink_response(self, response: str | dict[str, Any]) -> bool | None: ...
    async def handle_device_command(self, device_id: str, handler: str, message: Any) -> None: ...
    async def handle_device_topic(self, components: list[str], payload: Any) -> None: ...
    async def handle_homeassistant_message(self, payload: str) -> None: ...
    async def handle_service_command(self, handler: str, message: Any) -> None: ...
    async def heartbeat(self) -> None: ...
    async def main_loop(self) -> None: ...
    async def mqtt_on_connect(
        self, client: Client, userdata: dict[str, Any], flags: ConnectFlags, reason_code: ReasonCode, properties: Properties | None
    ) -> None: ...
    async def mqtt_on_disconnect(
        self, client: Client, userdata: Any, flags: DisconnectFlags, reason_code: ReasonCode, properties: Properties | None
    ) -> None: ...
    async def mqtt_on_log(self, client: Client, userdata: Any, paho_log_level: int, msg: str) -> None: ...
    async def mqtt_on_message(self, client: Client, userdata: Any, msg: MQTTMessage) -> None: ...
    async def mqtt_on_subscribe(self, client: Client, userdata: Any, mid: int, reason_code_list: list[ReasonCode], properties: Properties) -> None: ...
    async def mqttc_create(self) -> None: ...
    async def process_events_loop(self) -> None: ...
    async def process_events(self) -> None: ...
    async def publish_vision_request(self, device_id: str, image_b64: str, source: str) -> None: ...
    async def publish_device_availability(self, device_id: str, online: bool = True) -> None: ...
    async def publish_device_discovery(self, device_id: str) -> None: ...
    async def publish_device_image(self, device_id: str, type: str) -> None: ...
    async def publish_device_state(self, device_id: str, subject: str = "", sub: str = "") -> None: ...
    async def publish_service_availability(self, status: str = "online") -> None: ...
    async def publish_service_discovery(self) -> None: ...
    async def publish_service_state(self) -> None: ...
    async def queue_device_event(self, device_id: str, code: str, payload: Any) -> None: ...
    async def rediscover_all(self) -> None: ...
    async def refresh_all_devices(self) -> None: ...
    async def refresh_device_list(self) -> None: ...
    async def refresh_snapshot_all_devices(self) -> None: ...
    async def refresh_snapshot(self, device_id: str, type: str) -> None: ...
    async def set_arm_mode(self, device_id: str, switch: bool) -> Any | None: ...
    async def set_motion_detection(self, device_id: str, switch: bool) -> bool | None: ...
    async def set_nightvision(self, device_id: str, switch: str) -> bool | None: ...
    async def take_snapshot_from_device(self, device_id: str) -> None: ...

    def _assert_no_tuples(self, data: Any, path: str = "root") -> None: ...
    def _parse_device_topic(self, components: list[str]) -> list[str | None] | None: ...
    def _wrap_async(
        self,
        coro_func: Callable[..., Coroutine[Any, Any, _T]],
    ) -> Callable[..., None]: ...

    def classify_device(self, device: dict[str, str]) -> str | None: ...
    def get_platform(self, device_id: str) -> str: ...
    def get_component(self, device_id: str) -> dict[str, Any]: ...
    def get_device_availability_topic(self, device_id: str) -> str: ...
    def get_device_image_topic(self, device_id: str) -> str: ...
    def get_device_name(self, device_id: str) -> str: ...
    def get_device_state_topic(self, device_id: str, mode_name: str = "") -> str: ...
    def get_next_event(self) -> dict[str, Any] | None: ...
    def handle_signal(self, signum: int, frame: FrameType | None) -> Any: ...
    def heartbeat_ready(self) -> None: ...
    def increase_api_calls(self) -> None: ...
    def is_discovered(self, device_id: str) -> bool: ...
    def load_config(self, config_arg: Any | None = None) -> dict[str, Any]: ...
    def log_future_result(self, fut: concurrent.futures.Future) -> None: ...
    def mark_ready(self) -> None: ...
    def read_file(self, file_name: str) -> str: ...
    def _read_version_file(self) -> str: ...
    def reset_api_call_count(self) -> None: ...
    def resolve_camera_via_device(self, camera: dict[str, Any]) -> str | None: ...
    def safe_split_device(self, topic: str, segment: str) -> list[str]: ...
    def set_discovered(self, device_id: str) -> None: ...
    def upsert_device(self, device_id: str, **kwargs: dict[str, Any] | str | int | bool | None) -> bool: ...
    def upsert_state(self, device_id: str, **kwargs: dict[str, Any] | str | int | bool | None) -> bool: ...
